/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logica.ArbolNumeros;
import logica.DibujoArbolNumeros;

/**
 *
 * @author Nicolas
 */
public class FrameNumeros extends javax.swing.JFrame {

    ArbolNumeros arb = new ArbolNumeros();

    /**
     * Creates new form Pantalla
     */
    public FrameNumeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMostrarAltura = new javax.swing.JLabel();
        btnBusquedaAmplitud = new javax.swing.JButton();
        txtfNodoAgregar = new javax.swing.JTextField();
        btnAgregarNodos1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbPostOrdenMostrar = new javax.swing.JLabel();
        lbInOrdenMostrar = new javax.swing.JLabel();
        btnMostrarPostOrden = new javax.swing.JButton();
        btnMostrarInOrden = new javax.swing.JButton();
        btnCalcularAltura = new javax.swing.JButton();
        btnMostrarPreOrden = new javax.swing.JButton();
        lbPreOrdenMostrar = new javax.swing.JLabel();
        btnCalcularGrado = new javax.swing.JButton();
        lbBusquedaAmplitud = new javax.swing.JLabel();
        btnDibujarArbol = new javax.swing.JButton();
        lbMostrarGrado = new javax.swing.JLabel();
        btnNivelDeNodo = new javax.swing.JButton();
        lbMostrarNivel = new javax.swing.JLabel();
        btnVolverArbolNumeros = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 664));
        setMinimumSize(new java.awt.Dimension(640, 664));
        setPreferredSize(new java.awt.Dimension(640, 664));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMostrarAltura.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(lbMostrarAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 300, 30));

        btnBusquedaAmplitud.setBackground(new java.awt.Color(255, 255, 255));
        btnBusquedaAmplitud.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnBusquedaAmplitud.setText("Busqueda Amplitud");
        btnBusquedaAmplitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaAmplitudActionPerformed(evt);
            }
        });
        getContentPane().add(btnBusquedaAmplitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 150, -1));

        txtfNodoAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtfNodoAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 220, 30));

        btnAgregarNodos1.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregarNodos1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnAgregarNodos1.setText("Agregar nodo");
        btnAgregarNodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNodos1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarNodos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel3.setText("ARBOL BINARIO NÚMEROS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        lbPostOrdenMostrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(lbPostOrdenMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 300, 30));

        lbInOrdenMostrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(lbInOrdenMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 300, 30));

        btnMostrarPostOrden.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarPostOrden.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnMostrarPostOrden.setText("PostOrden");
        btnMostrarPostOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPostOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarPostOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, -1));

        btnMostrarInOrden.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarInOrden.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnMostrarInOrden.setText("InOrden");
        btnMostrarInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarInOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarInOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 150, -1));

        btnCalcularAltura.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcularAltura.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnCalcularAltura.setText("Altura");
        btnCalcularAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularAlturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcularAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 150, -1));

        btnMostrarPreOrden.setBackground(new java.awt.Color(255, 255, 255));
        btnMostrarPreOrden.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnMostrarPreOrden.setText("PreOrden");
        btnMostrarPreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPreOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarPreOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 150, -1));

        lbPreOrdenMostrar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(lbPreOrdenMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 300, 30));

        btnCalcularGrado.setBackground(new java.awt.Color(255, 255, 255));
        btnCalcularGrado.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnCalcularGrado.setText("Grado");
        btnCalcularGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularGradoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcularGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 150, -1));

        lbBusquedaAmplitud.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(lbBusquedaAmplitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 300, 30));

        btnDibujarArbol.setBackground(new java.awt.Color(255, 255, 255));
        btnDibujarArbol.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnDibujarArbol.setText("Dibujar arbol");
        btnDibujarArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDibujarArbolActionPerformed(evt);
            }
        });
        getContentPane().add(btnDibujarArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 150, -1));

        lbMostrarGrado.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(lbMostrarGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 300, 30));

        btnNivelDeNodo.setBackground(new java.awt.Color(255, 255, 255));
        btnNivelDeNodo.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnNivelDeNodo.setText("Nivel de un nodo");
        btnNivelDeNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNivelDeNodoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNivelDeNodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 150, -1));

        lbMostrarNivel.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        getContentPane().add(lbMostrarNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 300, 30));

        btnVolverArbolNumeros.setBackground(new java.awt.Color(255, 255, 255));
        btnVolverArbolNumeros.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnVolverArbolNumeros.setText("Volver");
        btnVolverArbolNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverArbolNumerosActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverArbolNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 520, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusquedaAmplitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaAmplitudActionPerformed
        ;
        lbBusquedaAmplitud.setText(arb.busquedaAmplitud());

    }//GEN-LAST:event_btnBusquedaAmplitudActionPerformed

    private void btnAgregarNodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNodos1ActionPerformed

        try {
            arb.insertar(Integer.parseInt(txtfNodoAgregar.getText()));
            txtfNodoAgregar.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor numérico.");
            txtfNodoAgregar.setText("");
        }

    }//GEN-LAST:event_btnAgregarNodos1ActionPerformed

    private void btnMostrarPostOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPostOrdenActionPerformed
        lbPostOrdenMostrar.setText(arb.UsarPostorden());        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarPostOrdenActionPerformed

    private void btnMostrarInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarInOrdenActionPerformed
        lbInOrdenMostrar.setText(arb.usarInorden());
    }//GEN-LAST:event_btnMostrarInOrdenActionPerformed

    private void btnCalcularAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularAlturaActionPerformed
        lbMostrarAltura.setText(String.valueOf(arb.calcularAltura()));


    }//GEN-LAST:event_btnCalcularAlturaActionPerformed

    private void btnMostrarPreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPreOrdenActionPerformed

        lbPreOrdenMostrar.setText(arb.usarPreorden());          // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarPreOrdenActionPerformed

    private void btnCalcularGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularGradoActionPerformed
        lbMostrarGrado.setText(String.valueOf(arb.calcularGrado()));        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularGradoActionPerformed

    private void btnDibujarArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDibujarArbolActionPerformed
        JFrame frame = new JFrame();
        DibujoArbolNumeros canvas = new DibujoArbolNumeros(arb);
        frame.add(canvas);
        frame.setSize(1200, 800);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnDibujarArbolActionPerformed

    private void btnNivelDeNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNivelDeNodoActionPerformed

        try {
            int inputNodo = Integer.parseInt(JOptionPane.showInputDialog(null, "Indique el nodo: "));
            lbMostrarNivel.setText(String.valueOf(arb.calcularNivel(inputNodo)));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor numérico.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNivelDeNodoActionPerformed

    private void btnVolverArbolNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverArbolNumerosActionPerformed
        Pantalla pantalla = new Pantalla();
        pantalla.setLocationRelativeTo(null);
        pantalla.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverArbolNumerosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNodos1;
    private javax.swing.JButton btnBusquedaAmplitud;
    private javax.swing.JButton btnCalcularAltura;
    private javax.swing.JButton btnCalcularGrado;
    private javax.swing.JButton btnDibujarArbol;
    private javax.swing.JButton btnMostrarInOrden;
    private javax.swing.JButton btnMostrarPostOrden;
    private javax.swing.JButton btnMostrarPreOrden;
    private javax.swing.JButton btnNivelDeNodo;
    private javax.swing.JButton btnVolverArbolNumeros;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbBusquedaAmplitud;
    private javax.swing.JLabel lbInOrdenMostrar;
    private javax.swing.JLabel lbMostrarAltura;
    private javax.swing.JLabel lbMostrarGrado;
    private javax.swing.JLabel lbMostrarNivel;
    private javax.swing.JLabel lbPostOrdenMostrar;
    private javax.swing.JLabel lbPreOrdenMostrar;
    private javax.swing.JTextField txtfNodoAgregar;
    // End of variables declaration//GEN-END:variables
}
