/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Nicolas
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSeleccionArbolLetras = new javax.swing.JButton();
        btnSeleccionArbolNumeros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(512, 234));
        setMinimumSize(new java.awt.Dimension(512, 234));
        setPreferredSize(new java.awt.Dimension(512, 234));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setText("Seleccione el tipo de dato del arbol");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jLabel4.setText("ARBOLES BINARIOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        btnSeleccionArbolLetras.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionArbolLetras.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnSeleccionArbolLetras.setText("Letras");
        btnSeleccionArbolLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionArbolLetrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionArbolLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 110, -1));

        btnSeleccionArbolNumeros.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionArbolNumeros.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnSeleccionArbolNumeros.setText("Números");
        btnSeleccionArbolNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionArbolNumerosActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionArbolNumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionArbolNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionArbolNumerosActionPerformed

        FrameNumeros frameNumeros = new FrameNumeros();
        frameNumeros.setLocationRelativeTo(null);
        frameNumeros.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnSeleccionArbolNumerosActionPerformed

    private void btnSeleccionArbolLetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionArbolLetrasActionPerformed
        FrameLetras frameLetras = new FrameLetras();
        frameLetras.setLocationRelativeTo(null);
        frameLetras.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionArbolLetrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionArbolLetras;
    private javax.swing.JButton btnSeleccionArbolNumeros;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
